=== ThunderBruce/XML-XSL-Schemas-y-DTD/XML_DTD_Schemas/OTROS/EmpYDep.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!-- DECLARACION EMPRESA -->
  <xs:element name="empresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="departamentos" type="listaDepartamento"/>
        <xs:element name="empleados" type="listaEmpleados"/>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="PrimaryKeyDep">
            <xs:selector xpath="empresa/departamentos/departamento"/>
            <xs:field xpath="dep_no"/>
          </xs:key>
    <xs:keyref name="ForeignKeyEmpDep" refer="PrimaryKeyDep">
          <xs:selector xpath="empresa/empleados/empleado"/>
          <xs:field xpath="dep_no"/>
          </xs:keyref>
    <xs:key name="PrimaryKeyEmp">
            <xs:selector xpath="empresa/empleados/empleado"/>
            <xs:field xpath="emp_no"/>
          </xs:key>
    <xs:keyref name="ForeignKeyEmpEmp" refer="PrimaryKeyEmp">
          <xs:selector xpath="empresa/empleados/empleado"/>
          <xs:field xpath="director"/>
          </xs:keyref>
  </xs:element>
  
    <xs:complexType name="listaDepartamento">
      <xs:sequence>
        <xs:element name="departamento" type="tipoDepartamento" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="listaEmpleados">
      <xs:sequence>
        <xs:element name="empleado" type="tipoEmpleado" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    
    <xs:complexType name="tipoDepartamento">
      <xs:sequence>
        <xs:element name="dep_no" type="xs:integer"/>
        <xs:element name="dnombre" type="xs:string"/>
        <xs:element name="localidad" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>

 
    <xs:complexType name="tipoEmpleado">
      <xs:sequence>
        <xs:element name="emp_no" type="xs:integer"/>
        <xs:element name="apellido" type="xs:string"/>
        <xs:element name="oficio" type="xs:string"/>
        <xs:element name="director" type="xs:string"/>
        <xs:element name="fecha_alta" type="xs:string"/>
        <xs:element name="salario" type="xs:float"/>
        <xs:element name="comision" type="xs:float" minOccurs="0"/>
        <xs:element name="dep_no" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
    

</xs:schema>

=== ThunderBruce/XML-XSL-Schemas-y-DTD/XML_DTD_Schemas/OTROS/EmpYDep.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="EmpyDep.xsd">
<departamentos>
<departamento>
<dep_no>10</dep_no>
<dnombre>CONTABILIDAD</dnombre>
<localidad>BARCELONA</localidad>
</departamento>
<departamento>
<dep_no>20</dep_no>
<dnombre>INVESTIGACION</dnombre>
<localidad>VALENCIA</localidad>
</departamento>
<departamento>
<dep_no>30</dep_no>
<dnombre>VENTAS</dnombre>
<localidad>MADRID</localidad>
</departamento>
<departamento>
<dep_no>40</dep_no>
<dnombre>PRODUCCION</dnombre>
<localidad>SEVILLA</localidad>
</departamento>
</departamentos>
<empleados>
<empleado>
<emp_no>7839</emp_no>
<apellido>REY</apellido>
<oficio>PRESIDENTE</oficio>
<director></director>
<fecha_alta>1981-11-17</fecha_alta>
<salario>6000.00</salario>
<dep_no>10</dep_no>
</empleado>
<empleado>
<emp_no>7698</emp_no>
<apellido>GARRIDO</apellido>
<oficio>DIRECTOR</oficio>
<director>7839</director>
<fecha_alta>1981-5-1</fecha_alta>
<salario>3850.00</salario>
<dep_no>30</dep_no>
</empleado>
<empleado>
<emp_no>7499</emp_no>
<apellido>ALONSO</apellido>
<oficio>VENDEDOR</oficio>
<director>7698</director>
<fecha_alta>1981-2-20</fecha_alta>
<salario>1400.00</salario>
<comision>400.00</comision>
<dep_no>30</dep_no>
</empleado>
</empleados>
</empresa>
